Databases:
  # tell pyannote.database where to find AMI wav files.
  # {uri} is a placeholder for the session name (eg. ES2004c).
  # E:/Rich_Transcription/Processed_Files/prepped_audio is a placeholder for the normalized wavs directory
  anime_finetune: "E:/Rich_Transcription/Processed_Files/prepped_audio/{uri}.wav"
Protocols:
  anime_finetune:
    SpeakerDiarization:
      full:
        train:
            uri: E:/Rich_Transcription/Processed_Files/lists/train.full.txt
            annotation: "E:/Rich_Transcription/Processed_Files/rttm_files/{uri}.rttm"
            annotated: "E:/Rich_Transcription/Processed_Files/uems/{uri}.uem"
        development:
            uri: E:/Rich_Transcription/Processed_Files/lists/dev.full.txt
            annotation: "E:/Rich_Transcription/Processed_Files/rttm_files/{uri}.rttm"
            annotated: "E:/Rich_Transcription/Processed_Files/uems/{uri}.uem"
        test:
            uri: E:/Rich_Transcription/Processed_Files/lists/test.full.txt
            annotation: "E:/Rich_Transcription/Processed_Files/rttm_files/{uri}.rttm"
            annotated: "E:/Rich_Transcription/Processed_Files/uems/{uri}.uem"
      mini:
        train:
            uri: E:/Rich_Transcription/Processed_Files/lists  /train.mini.txt
            annotation: "E:/Rich_Transcription/Processed_Files/rttm_files/{uri}.rttm"
            annotated: "E:/Rich_Transcription/Processed_Files/uems/{uri}.uem"
        development:
            uri: E:/Rich_Transcription/Processed_Files/lists/dev.mini.txt
            annotation: "E:/Rich_Transcription/Processed_Files/rttm_files/{uri}.rttm"
            annotated: "E:/Rich_Transcription/Processed_Files/uems/{uri}.uem"
        test:
            uri: E:/Rich_Transcription/Processed_Files/lists/test.mini.txt
            annotation: "E:/Rich_Transcription/Processed_Files/rttm_files/{uri}.rttm"
            annotated: "E:/Rich_Transcription/Processed_Files/uems/{uri}.uem"